version: 2
updates:
    # Dependencies for Maven
    - package-ecosystem: 'maven'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 15
      ignore:
          - dependency-name: "aws-java-sdk-bom"

    # Dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
